name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        env:
          DATA_DIR: /tmp/localstack/data
        ports: ["4566:4566"]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Configure localstack
      run: |
        aws configure set aws_access_key_id localstack
        aws configure set aws_secret_access_key localstack
        aws configure set default.region eu-west-2
        aws mb s3://sample-bucket-1 --endpoint-url=http://localstack:4566
        aws mb s3://sample-bucket-1 --endpoint-url=http://localstack:4566
        aws mb s3://sample-bucket-1 --endpoint-url=http://localstack:4566
      
    - name: Build
      run: go build -v ./app/...

      
    - name: Test
      run: go test -v ./app/...
